name: nodejs_tut
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  http: ^1.4.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
